Apm 992 cache scoping
NHSDigital/identity-service-api pull request #89
Opened 2020-11-05 16:25 UTC by HenryIwanejko

## Summary
* Update tests to run on PR
* Add tests to check state scope

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2020-11-06 09:36 UTC, Sourceless requested changes
A couple code smells in here that need more attention, but otherwise good work 👍🏻

2020-11-06 09:36 UTC, Sourceless commented on api_tests/scripts/authenticator.py
> +        with self.session.post(
Is there any particular need to use a context manager here?

2020-11-06 09:36 UTC, Sourceless commented on api_tests/scripts/generic_request.py
> +            return True if not return_response else response
This smells like it should be two functions instead of one with a flag to change its return type

2020-11-06 09:36 UTC, Sourceless commented on api_tests/scripts/generic_request.py
> +                       **kwargs) -> bool or object:
I don't think `bool or object` is actually valid here, it should be `Union[bool, object]`.

That said as well, `object` is a bit too broad of a return type.

I think this function is probably doing too much and needs to be split in two, OR just return the response and do the bool conversion (checking truthiness) a level up

2020-11-06 09:36 UTC, Sourceless commented on api_tests/scripts/authenticator.py
> +        request_state = "1234567890"
Should this be a unique value? e.g. a UUID?

2020-11-06 09:36 UTC, Sourceless commented on api_tests/scripts/authenticator.py
> +    def _get_state(self) -> str:
Consider using `@property` decorator here.

2020-11-06 09:36 UTC, Sourceless commented on api_tests/scripts/generic_request.py
> +                       **kwargs) -> bool or object:
Or any if the other `type or othertype` bits for that matter.

2020-11-06 09:36 UTC, Sourceless commented on api_tests/tests/oauth/test_oauth_endpoints.py
> +    @pytest.mark.skip("Skipping to merge")
Why are these being skipped?

2020-11-10 10:04 UTC, alexhawdon approved these changes

2020-11-10 10:18 UTC, alexhawdon approved these changes

2020-11-10 10:19 UTC, merged